; Automatically converted to only require STRIPS and negative preconditions

(define (problem transport-three-cities-sequential-5nodes-1000size-4degree-100mindistance-3trucks-9packages-2012seed)
  (:domain transport)
  (:objects city-1-loc-1 city-2-loc-1 city-3-loc-1 city-1-loc-2 city-2-loc-2 city-3-loc-2 city-1-loc-3 city-2-loc-3 city-3-loc-3 city-1-loc-4 city-2-loc-4 city-3-loc-4 city-1-loc-5 city-2-loc-5 city-3-loc-5 truck-1 truck-2 truck-3 package-1 package-2 package-3 package-4 package-5 package-6 package-7 package-8 package-9 capacity-0 capacity-1 capacity-2 capacity-3 capacity-4)
  (:init
    (capacity-predecessor capacity-0 capacity-1)
    (capacity-predecessor capacity-1 capacity-2)
    (capacity-predecessor capacity-2 capacity-3)
    (capacity-predecessor capacity-3 capacity-4)
    (road city-1-loc-3 city-1-loc-1)
    (road city-1-loc-1 city-1-loc-3)
    (road city-1-loc-3 city-1-loc-2)
    (road city-1-loc-2 city-1-loc-3)
    (road city-1-loc-4 city-1-loc-2)
    (road city-1-loc-2 city-1-loc-4)
    (road city-1-loc-4 city-1-loc-3)
    (road city-1-loc-3 city-1-loc-4)
    (road city-1-loc-5 city-1-loc-2)
    (road city-1-loc-2 city-1-loc-5)
    (road city-1-loc-5 city-1-loc-3)
    (road city-1-loc-3 city-1-loc-5)
    (road city-1-loc-5 city-1-loc-4)
    (road city-1-loc-4 city-1-loc-5)
    (road city-2-loc-2 city-2-loc-1)
    (road city-2-loc-1 city-2-loc-2)
    (road city-2-loc-4 city-2-loc-1)
    (road city-2-loc-1 city-2-loc-4)
    (road city-2-loc-4 city-2-loc-2)
    (road city-2-loc-2 city-2-loc-4)
    (road city-2-loc-4 city-2-loc-3)
    (road city-2-loc-3 city-2-loc-4)
    (road city-2-loc-5 city-2-loc-1)
    (road city-2-loc-1 city-2-loc-5)
    (road city-2-loc-5 city-2-loc-2)
    (road city-2-loc-2 city-2-loc-5)
    (road city-2-loc-5 city-2-loc-3)
    (road city-2-loc-3 city-2-loc-5)
    (road city-2-loc-5 city-2-loc-4)
    (road city-2-loc-4 city-2-loc-5)
    (road city-3-loc-2 city-3-loc-1)
    (road city-3-loc-1 city-3-loc-2)
    (road city-3-loc-3 city-3-loc-1)
    (road city-3-loc-1 city-3-loc-3)
    (road city-3-loc-3 city-3-loc-2)
    (road city-3-loc-2 city-3-loc-3)
    (road city-3-loc-4 city-3-loc-1)
    (road city-3-loc-1 city-3-loc-4)
    (road city-3-loc-4 city-3-loc-2)
    (road city-3-loc-2 city-3-loc-4)
    (road city-3-loc-4 city-3-loc-3)
    (road city-3-loc-3 city-3-loc-4)
    (road city-3-loc-5 city-3-loc-1)
    (road city-3-loc-1 city-3-loc-5)
    (road city-3-loc-5 city-3-loc-2)
    (road city-3-loc-2 city-3-loc-5)
    (road city-3-loc-5 city-3-loc-3)
    (road city-3-loc-3 city-3-loc-5)
    (road city-3-loc-5 city-3-loc-4)
    (road city-3-loc-4 city-3-loc-5)
    (road city-1-loc-1 city-2-loc-3)
    (road city-2-loc-3 city-1-loc-1)
    (road city-1-loc-1 city-3-loc-3)
    (road city-3-loc-3 city-1-loc-1)
    (road city-2-loc-1 city-3-loc-1)
    (road city-3-loc-1 city-2-loc-1)
    (at package-1 city-3-loc-4)
    (at package-2 city-2-loc-5)
    (at package-3 city-3-loc-4)
    (at package-4 city-3-loc-2)
    (at package-5 city-1-loc-3)
    (at package-6 city-1-loc-3)
    (at package-7 city-1-loc-1)
    (at package-8 city-2-loc-2)
    (at package-9 city-3-loc-1)
    (at truck-1 city-2-loc-4)
    (capacity truck-1 capacity-3)
    (at truck-2 city-2-loc-1)
    (capacity truck-2 capacity-3)
    (at truck-3 city-3-loc-4)
    (capacity truck-3 capacity-2)
    (location city-1-loc-1)
    (location city-2-loc-1)
    (location city-3-loc-1)
    (location city-1-loc-2)
    (location city-2-loc-2)
    (location city-3-loc-2)
    (location city-1-loc-3)
    (location city-2-loc-3)
    (location city-3-loc-3)
    (location city-1-loc-4)
    (location city-2-loc-4)
    (location city-3-loc-4)
    (location city-1-loc-5)
    (location city-2-loc-5)
    (location city-3-loc-5)
    (vehicle truck-1)
    (locatable truck-1)
    (vehicle truck-2)
    (locatable truck-2)
    (vehicle truck-3)
    (locatable truck-3)
    (package package-1)
    (locatable package-1)
    (package package-2)
    (locatable package-2)
    (package package-3)
    (locatable package-3)
    (package package-4)
    (locatable package-4)
    (package package-5)
    (locatable package-5)
    (package package-6)
    (locatable package-6)
    (package package-7)
    (locatable package-7)
    (package package-8)
    (locatable package-8)
    (package package-9)
    (locatable package-9)
    (capacity-number capacity-0)
    (capacity-number capacity-1)
    (capacity-number capacity-2)
    (capacity-number capacity-3)
    (capacity-number capacity-4)
  )
  (:goal
    (and
      (at package-5 city-2-loc-3)
    )
  )
)
